# Generated by Django 3.0.8 on 2020-08-20 08:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('prof_photo', models.ImageField(upload_to='pics/profiles/')),
                ('user', models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=1000)),
                ('repository_link', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('project_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('user_interface', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_experience', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('responsiveness', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('design_average', models.IntegerField()),
                ('functionality', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('io', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('usability_average', models.IntegerField()),
                ('content_average', models.IntegerField()),
                ('total_average', models.IntegerField()),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Projects')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('for_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Projects')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectawards.Profile')),
            ],
        ),
    ]
